import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import { CalendarDays, Users, FileText, ClipboardList, Wallet, Camera, Plus, Search, UserRound, Phone, MapPin, Wrench, Menu, X, ShieldCheck, Building2, MessageCircle, Navigation, CheckCircle2, Bell, Hammer, LogOut, Lock, Save, Trash2 } from 'lucide-react';
import './style.css';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';
const supabase = supabaseUrl && supabaseAnonKey ? createClient(supabaseUrl, supabaseAnonKey) : null;

const demoUser = { email: 'admin@sb.com', role: 'admin', name: 'Rodrigo' };

function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
function whatsappLink(phone){const cleaned=String(phone||'').replace(/\D/g,'');return `https://wa.me/55${cleaned.startsWith('55')?cleaned.slice(2):cleaned}`;}
function mapsLink(endereco){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(endereco||'')}`;}

function App(){
 const [session,setSession]=useState(null); const [profile,setProfile]=useState(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{ if(!supabase){setProfile(demoUser);setLoading(false);return;} supabase.auth.getSession().then(({data})=>{setSession(data.session);}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe();},[]);
 useEffect(()=>{ async function loadProfile(){ if(!supabase){return;} if(!session?.user){setProfile(null);setLoading(false);return;} const {data}=await supabase.from('profiles').select('*').eq('id',session.user.id).single(); setProfile(data||{email:session.user.email,role:'funcionario',name:session.user.email}); setLoading(false);} loadProfile();},[session]);
 if(loading) return <div className="center">Carregando...</div>;
 if(!profile) return <Login />;
 return <Dashboard profile={profile} />;
}

function Login(){
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [msg,setMsg]=useState('');
 async function signIn(){ if(!supabase){setMsg('Configure o Supabase no arquivo .env para ativar login real.');return;} const {error}=await supabase.auth.signInWithPassword({email,password}); if(error)setMsg(error.message); }
 return <div className="loginPage"><div className="loginCard"><Logo/><h1>SB Gestão</h1><p>Acesse sua agenda, clientes, orçamentos e serviços.</p><input placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Senha" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={signIn}><Lock size={18}/> Entrar</button>{msg&&<small>{msg}</small>}<div className="demo"><b>Modo demonstração:</b><br/>Sem Supabase configurado, o sistema abre como admin automaticamente.</div></div></div>
}
function Logo(){return <div className="logo"><span className="red">S</span><span className="blue">B</span><small>Serviços Gerais</small></div>}

function Dashboard({profile}){
 const isAdmin=profile.role==='admin'; const [active,setActive]=useState('painel'); const [menu,setMenu]=useState(false);
 const [clientes,setClientes]=useState([{id:1,nome:'Imobiliária Parceira',telefone:'45999990000',endereco:'Centro - Medianeira',origem:'Imobiliária',status:'Ativo'},{id:2,nome:'João Silva',telefone:'45988880000',endereco:'Bairro Itaipu',origem:'Google',status:'Orçamento'}]);
 const [servicos,setServicos]=useState([{id:1,data:'2026-05-29',hora:'08:00',cliente:'João Silva',servico:'Desentupimento',endereco:'Centro - Medianeira',responsavel:'Equipe 1',valor:250,status:'Agendado',obs:''},{id:2,data:'2026-05-29',hora:'14:00',cliente:'Maria Souza',servico:'Reparo hidráulico',endereco:'Jardim Irene',responsavel:'Rodrigo',valor:400,status:'Em andamento',obs:''}]);
 const [orcamentos,setOrcamentos]=useState([{id:1,cliente:'Carlos',servico:'Pintura residencial',valor:2400,status:'Enviado',retorno:'2 dias sem retorno'},{id:2,cliente:'Larissa',servico:'Troca de disjuntor',valor:280,status:'Aprovado',retorno:'Agendar execução'}]);
 const [financeiro,setFinanceiro]=useState([{id:1,descricao:'Desentupimento - João Silva',tipo:'Entrada',valor:250,status:'Recebido'},{id:2,descricao:'Material hidráulico',tipo:'Saída',valor:85,status:'Pago'}]);
 const nav=[['painel','Painel',Building2],['agenda','Agenda',CalendarDays],['clientes','Clientes',Users],['orcamentos','Orçamentos',FileText],['os','Ordens de Serviço',ClipboardList],['financeiro','Financeiro',Wallet],['obras','Obras',Hammer],['fotos','Fotos',Camera]];
 const title=nav.find(n=>n[0]===active)?.[1]||'Painel';
 async function logout(){ if(supabase) await supabase.auth.signOut(); location.reload(); }
 function Sidebar(){return <aside className="sidebar"><Logo/><nav>{nav.map(([id,label,Icon])=><button key={id} onClick={()=>{setActive(id);setMenu(false)}} className={active===id?'on':''}><Icon size={18}/>{label}</button>)}</nav><div className="access"><ShieldCheck size={18}/><b>Acesso</b><p>{isAdmin?'Administrador: acesso total':'Funcionário: atualiza serviços e fotos'}</p></div><button className="logout" onClick={logout}><LogOut size={17}/> Sair</button></aside>}
 return <div className="app"><div className="desktop"><Sidebar/></div>{menu&&<div className="overlay"><button className="close" onClick={()=>setMenu(false)}><X/></button><Sidebar/></div>}<main><header><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><div><h1>{title}</h1><p>SB Gestão — controle completo da operação.</p></div><div className="user">{profile.name||profile.email}</div></header><section>{active==='painel'&&<Painel servicos={servicos} orcamentos={orcamentos} financeiro={financeiro}/>} {active==='agenda'&&<Agenda isAdmin={isAdmin} servicos={servicos} setServicos={setServicos}/>} {active==='clientes'&&<Clientes isAdmin={isAdmin} clientes={clientes} setClientes={setClientes}/>} {active==='orcamentos'&&<Orcamentos isAdmin={isAdmin} orcamentos={orcamentos} setOrcamentos={setOrcamentos}/>} {active==='os'&&<OS/>} {active==='financeiro'&&<Financeiro isAdmin={isAdmin} financeiro={financeiro} setFinanceiro={setFinanceiro}/>} {active==='obras'&&<Obras/>} {active==='fotos'&&<Fotos/>}</section></main></div>
}
function Badge({children}){let t=String(children); let c=t.includes('Finalizado')||t.includes('Aprovado')||t.includes('Recebido')||t.includes('Ativo')?'green':t.includes('Enviado')||t.includes('Orçamento')||t.includes('A receber')?'yellow':t.includes('Em andamento')||t.includes('Agendado')||t.includes('Negociação')?'blue':'red'; return <span className={'badge '+c}>{children}</span>}
function Painel({servicos,orcamentos,financeiro}){const ent=financeiro.filter(f=>f.tipo==='Entrada').reduce((s,f)=>s+Number(f.valor),0); const sai=financeiro.filter(f=>f.tipo==='Saída').reduce((s,f)=>s+Number(f.valor),0); const cards=[['Serviços',servicos.length,CalendarDays],['Orçamentos pendentes',orcamentos.filter(o=>o.status!=='Aprovado').length,FileText],['Entradas',money(ent),Wallet],['Lucro estimado',money(ent-sai),CheckCircle2]]; return <><div className="cards">{cards.map(([l,v,I])=><div className="card stat" key={l}><div><p>{l}</p><h2>{v}</h2></div><I/></div>)}</div><div className="card"><h2>Próximos serviços</h2><ServiceTable servicos={servicos}/></div></>}
function ServiceTable({servicos}){return <div className="table"><table><thead><tr><th>Data</th><th>Hora</th><th>Cliente</th><th>Serviço</th><th>Endereço</th><th>Status</th></tr></thead><tbody>{servicos.map(s=><tr key={s.id}><td>{s.data}</td><td><b>{s.hora}</b></td><td>{s.cliente}</td><td>{s.servico}</td><td><a href={mapsLink(s.endereco)} target="_blank">{s.endereco}</a></td><td><Badge>{s.status}</Badge></td></tr>)}</tbody></table></div>}
function Agenda({isAdmin,servicos,setServicos}){const blank={data:'',hora:'',cliente:'',servico:'',endereco:'',responsavel:'',valor:'',status:'Agendado',obs:''}; const [f,setF]=useState(blank); function add(){if(!f.cliente||!f.servico)return;setServicos([{...f,id:Date.now(),valor:Number(f.valor||0)},...servicos]);setF(blank)} function update(id,patch){setServicos(servicos.map(s=>s.id===id?{...s,...patch}:s))} return <div className="grid"><div className="card wide"><h2>Agendar serviço</h2>{isAdmin?<Form f={f} setF={setF} fields={['data','hora','cliente','servico','endereco','responsavel','valor']} add={add}/>:<p>Funcionários podem atualizar apenas status e observações.</p>}</div>{servicos.map(s=><div className="card" key={s.id}><div className="row"><h2>{s.hora}</h2><Badge>{s.status}</Badge></div><p>{s.data}</p><h3>{s.servico}</h3><p><UserRound size={15}/> {s.cliente}</p><p><MapPin size={15}/> {s.endereco}</p><p><Wrench size={15}/> {s.responsavel}</p>{isAdmin&&<b>{money(s.valor)}</b>}<select value={s.status} onChange={e=>update(s.id,{status:e.target.value})}><option>Agendado</option><option>Em andamento</option><option>Concluído</option><option>Precisa de retorno</option></select><textarea placeholder="Observações do serviço" value={s.obs} onChange={e=>update(s.id,{obs:e.target.value})}/><a href={mapsLink(s.endereco)} target="_blank"><button><Navigation size={16}/> Abrir rota</button></a></div>)}</div>}
function Form({f,setF,fields,add}){return <><div className="form">{fields.map(k=><input key={k} type={k==='data'?'date':k==='hora'?'time':k==='valor'?'number':'text'} placeholder={k} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>)}</div><button onClick={add}><Plus size={16}/> Salvar</button></>}
function Clientes({isAdmin,clientes,setClientes}){const blank={nome:'',telefone:'',endereco:'',origem:'Instagram',status:'Ativo'}; const [f,setF]=useState(blank); function add(){if(!f.nome||!f.telefone)return;setClientes([{...f,id:Date.now()},...clientes]);setF(blank)} return <div className="grid"><div className="card wide"><h2>Novo cliente</h2>{isAdmin?<Form f={f} setF={setF} fields={['nome','telefone','endereco','origem']} add={add}/>:<p>Acesso restrito.</p>}</div>{clientes.map(c=><div className="card" key={c.id}><div className="row"><h2>{c.nome}</h2><Badge>{c.status}</Badge></div><p><Phone size={15}/> {c.telefone}</p><p><MapPin size={15}/> {c.endereco}</p><p>Origem: {c.origem}</p><div className="actions"><a href={whatsappLink(c.telefone)} target="_blank"><button className="greenBtn"><MessageCircle size={16}/> WhatsApp</button></a><a href={mapsLink(c.endereco)} target="_blank"><button><MapPin size={16}/> Maps</button></a></div></div>)}</div>}
function Orcamentos({isAdmin,orcamentos,setOrcamentos}){const blank={cliente:'',servico:'',valor:'',status:'Enviado',retorno:'Retornar em 2 dias'}; const [f,setF]=useState(blank); function add(){if(!f.cliente||!f.servico)return;setOrcamentos([{...f,id:Date.now(),valor:Number(f.valor||0)},...orcamentos]);setF(blank)} return <div className="stack"><div className="card"><h2>Novo orçamento</h2>{isAdmin?<Form f={f} setF={setF} fields={['cliente','servico','valor','retorno']} add={add}/>:<p>Acesso restrito.</p>}</div>{orcamentos.map(o=><div className="card line" key={o.id}><div><h2>{o.cliente}</h2><p>{o.servico}</p></div><b>{money(o.valor)}</b><Badge>{o.status}</Badge><p><Bell size={15}/> {o.retorno}</p></div>)}</div>}
function OS(){return <div className="card"><h2>Nova ordem de serviço</h2><p>Preencha e gere uma OS. A geração de PDF entra na próxima etapa.</p><div className="form">{['Cliente','Telefone','Endereço','Tipo de serviço','Material','Mão de obra','Valor total','Responsável'].map(x=><input key={x} placeholder={x}/>)}</div><textarea placeholder="Descrição do serviço realizado"/><button><FileText size={16}/> Gerar OS</button></div>}
function Financeiro({isAdmin,financeiro,setFinanceiro}){const blank={descricao:'',tipo:'Entrada',valor:'',status:'A receber'}; const [f,setF]=useState(blank); function add(){if(!f.descricao||!f.valor)return;setFinanceiro([{...f,id:Date.now(),valor:Number(f.valor||0)},...financeiro]);setF(blank)} if(!isAdmin)return <div className="card"><h2>Financeiro</h2><p>Somente administradores têm acesso ao financeiro.</p></div>; return <div className="stack"><div className="card"><h2>Lançamento financeiro</h2><div className="form"><input placeholder="Descrição" value={f.descricao} onChange={e=>setF({...f,descricao:e.target.value})}/><select value={f.tipo} onChange={e=>setF({...f,tipo:e.target.value})}><option>Entrada</option><option>Saída</option></select><input type="number" placeholder="Valor" value={f.valor} onChange={e=>setF({...f,valor:e.target.value})}/><select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option>Recebido</option><option>A receber</option><option>Pago</option><option>A pagar</option></select></div><button onClick={add}><Save size={16}/> Lançar</button></div>{financeiro.map(f=><div className="card line" key={f.id}><h3>{f.descricao}</h3><p>{f.tipo}</p><b>{money(f.valor)}</b><Badge>{f.status}</Badge></div>)}</div>}
function Obras(){return <div className="grid">{['Fundação','Alvenaria','Elétrica/Hidráulica','Cobertura','Acabamento','Entrega'].map((e,i)=><div className="card" key={e}><p>Etapa {i+1}</p><h2>{e}</h2><p>Registrar responsável, prazo, materiais e fotos.</p></div>)}</div>}
function Fotos(){return <div className="grid">{['Antes','Durante','Depois'].map(x=><div className="card upload" key={x}><Camera/><h2>Foto do {x}</h2><p>Salvar fotos por serviço para histórico e marketing.</p><button><Plus size={16}/> Adicionar foto</button></div>)}</div>}

createRoot(document.getElementById('root')).render(<App/>);
